package com.example.homeworksecond

object ContactsDataList {
    fun getContacts() = listOf(
        Contactdata("https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession"),
        Contactdata("https://www.imgonline.com.ua/examples/bee-on-daisy.jpg",
            "User Name","Profession")
    )

}